### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by moorepants** [paholg/spring-sim#1]
Hi,

I'm interested in using the code your wrote to draw a spring in a library I wrote. You do not have a license specified for this code. I was wondering if you'd be willing to license it with a MIT/BSD style license? Or give me specific permission to use the draw spring function and license it as a I see fit for my library?

Thanks,

Jason

**Comment by paholg** [comment]
Hi Jason,

You have permission to use it as you like, with or without attribution. If
you make a PR to add a MIT/Apache license, I will happily accept it.

Have fun!

- Paho

**Comment by moorepants** [comment]
Great thanks!
